[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "#414868"
blue = "#7aa2f7"
cyan = "#7dcfff"
green = "#9ece6a"
magenta = "#bb9af7"
red = "#f7768e"
white = "#c0caf5"
yellow = "#e0af68"

[colors.cursor]
cursor = "#c0caf5"
text = "#0f111a"

[colors.normal]
black = "#15161e"
blue = "#7aa2f7"
cyan = "#7dcfff"
green = "#9ece6a"
magenta = "#bb9af7"
red = "#f7768e"
white = "#a9b1d6"
yellow = "#e0af68"

[colors.primary]
background = "#222436"
foreground = "#c0caf5"

[colors.selection]
background = "#33467c"
text = "#ffffff"

[cursor]
blink_interval = 750

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "Fira Code"
style = "Bold"

[font.italic]
family = "Fira Code"
style = "Italic"

[font.normal]
family = "Fira Code"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 5

[window]
decorations = "full"
dynamic_title = true

[window.padding]
x = 6
y = 6

[keyboard]
